CREATE TABLE IF NOT EXISTS users (
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
username VARCHAR(255) NOT NULL,
password VARCHAR(20) NOT NULL,
roles VARCHAR(20) NOT NULL,
PRIMARY KEY(id));