CREATE TABLE IF NOT EXISTS avto (
id BIGINT NOT NULL AUTO_INCREMENT,
brant VARCHAR(20) NOT NULL,
models VARCHAR(20) NOT NULL,
id_users BIGINT NOT NULL,
PRIMARY KEY(id),
CONSTRAINT avto_ibfk_1 FOREIGN KEY (id_users) REFERENCES users (id));
