CREATE TABLE IF NOT EXISTS imploer (
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
id_jobs BIGINT NOT NULL,
PRIMARY KEY(id),
CONSTRAINT imploer_ibfk_1 FOREIGN KEY (id_jobs) REFERENCES jobs(id));
