CREATE TABLE IF NOT EXISTS sto (
id BIGINT NOT NULL AUTO_INCREMENT,
id_avto BIGINT NOT NULL,
id_imploer BIGINT NOT NULL,
data DATE NOT NULL,
PRIMARY KEY(id),
CONSTRAINT sto_ibfk_1 FOREIGN KEY (id_avto) REFERENCES avto(id),
CONSTRAINT sto_ibfk_2 FOREIGN KEY (id_imploer) REFERENCES imploer(id));
