CREATE TABLE IF NOT EXISTS serv (
id BIGINT NOT NULL AUTO_INCREMENT,
id_jobs BIGINT NOT NULL,
id_sto BIGINT NOT NULL,
data DATE NOT NULL,
serv_price FLOAT NOT NULL,
PRIMARY KEY(id),
CONSTRAINT serv_ibfk_1 FOREIGN KEY (id_jobs) REFERENCES jobs(id),
CONSTRAINT serv_ibfk_2 FOREIGN KEY (id_sto) REFERENCES sto(id));
